### ISSUE TITLE
Feature Request: Implement a dark mode

### ISSUE THREAD

**Issue by iswarmondal** [pocketbase/site#11]
### Does the site has a dark mode? Can't find the toggle button
It would be very nice to have a dark mode for the site and the docs. The background is completely white and it seems to be very bright for working at night

The front end is built with Svelte so I'm more than happy to open a PR implementing the dark mode on the site.

**Comment by ganigeorgiev** [comment]
Similar to the Dark mode request in the main repo (https://github.com/pocketbase/pocketbase/issues/407), this for now is not planned since it will be hard to maintain. It'll be added once we reach a more stable version.
