### ISSUE TITLE
Sendinblue has been renamed to Brevo

### ISSUE THREAD

**Issue by CrispyBaguette** [pocketbase/site#25]
The link in the doc should reflect that change.

Source: [annoncement on Brevo's website](https://www.brevo.com/blog/becoming-brevo/).

https://github.com/pocketbase/site/blob/3db8ca043aa30b6dd7b1f794317fdfa35bd18421/src/routes/(app)/docs/going-to-production/%2Bpage.svelte#L215

**Comment by ganigeorgiev** [comment]
Thanks, I've merged the change in the develop branch. It'll be available with the PocketBase v0.16.0 changes (most likely next week).
