### ISSUE TITLE
Feature Request: Add a tutorial page.

### ISSUE THREAD

**Issue by H1Mohamed** [pocketbase/site#45]
well pocketbase's docs arent that clear....like relations are still hard to understand, so making a tutorial page like the one on kit.svelte.dev
will really help, and will even more if you use the testing pocketbase Ui instance to teach both the sdk's in go and js with the admin Ui
It will take a lot of time, but it will be a great investment of time for the future of Pocketbase

**Comment by ganigeorgiev** [comment]
Thanks for the idea.

Docs definitely need more work and will be improved before the stable v1.0.0, but I don't think I'll have the time to work on interactive tutorial.

I'll close the issue for now as there is no direct actionable item, but may revisit it later.
