### ISSUE TITLE
Logs API documentation points to outdated endpoint urls

### ISSUE THREAD

**Issue by m29h** [pocketbase/site#49]
With pocketbase >=v0.20.0 the Logs API endpoints got renamed from /api/logs/requests/... to /api/logs/...

[original commit with the change](https://github.com/pocketbase/pocketbase/commit/821aae4a624c86cea03c723ec16a85d5eb188788)
This is currently not yet reflected in the documentation [https://pocketbase.io/docs/api-logs](https://pocketbase.io/docs/api-logs)

**Comment by ganigeorgiev** [comment]
Thanks! It should be fixed now.
