### ISSUE TITLE
Error in Collections page

### ISSUE THREAD

**Issue by vigneshksaithal** [pocketbase/site#56]
<img width="849" alt="Screenshot 2024-03-03 at 12 28 17 PM" src="https://github.com/pocketbase/site/assets/60360863/88300149-2b0e-421f-bb44-74cfb4dec3f0">

In the above image should ```author``` be ```author.id``` instead? as it is being checked with ```@request.auth.id```.

**Comment by ganigeorgiev** [comment]
No. For single `relation` fields `author` and `author.id` is the same because the plain field value (`author`) contains the id as string (for multuple `relation` the plain field value is a serialized json array, ex. `["id1","id2"]`).
