### ISSUE TITLE
Feat request: search through document

### ISSUE THREAD

**Issue by thnt** [pocketbase/site#57]
May be add algolia integration

**Comment by H1Mohamed** [comment]
no need to use algolia, we can just use pocketbase 🤔

**Comment by ganigeorgiev** [comment]
This has been implemented in the `develop` branch together with the new docs for v0.23.0 (the search index is statically generated using https://github.com/cloudcannon/pagefind).

It will be publicly available with the v0.23.0 stable release soon (_there are no ETAs yet_).
