### ISSUE TITLE
Landing page button color on iOS

### ISSUE THREAD

**Issue by felix-schindler** [pocketbase/site#59]
> [!NOTE]
> This is only a issue if you want to have to same look across all browsers

The default button color on iOS is `blue`, therefore it needs to be overwritten to `inherit` to look the same across browsers.

![9DEB1C61-FC31-45BD-A4CD-624403E859A7_1_102_o](https://github.com/pocketbase/site/assets/65357346/986dd1d4-3e89-4692-8ed4-bd8b1b2486db)

**Comment by ganigeorgiev** [comment]
I've updated the default `button` styles but even if it is not fixed I think it is OK.

**Comment by felix-schindler** [comment]
it's fixed

<img src="https://github.com/pocketbase/site/assets/65357346/7f3f65ff-fff6-4f87-98a2-23e6b5f29134" alt="showing the pocketbase.io home page" width="200px">
