### ISSUE TITLE
 Request to Contribute to Documentation for v0.23.0 Changes (with Examples and Guides)

### ISSUE THREAD

**Issue by GSGSDgggdzez** [pocketbase/site#65]
Hello,

I would love to contribute by updating the documentation to reflect the recent changes in **PocketBase v0.23.0**. I understand from the [PocketBase project board](https://github.com/orgs/pocketbase/projects/2/views/1?layout=table&pane=issue&itemId=82322350) that there is a task titled *"New documentation reflecting the v0.23.0 changes (+ maybe section for examples/guides)."* This task seems to be about enhancing the documentation with updated content related to the new release.

I’d be happy to take on this task and would like to ask if you can assign it to me. It would be really helpful if you could also clarify exactly what you're looking for in the documentation update.

### **What I Plan to Do**:
- Update the main documentation to reflect all significant changes introduced in **v0.23.0**.
- Add a **section with practical examples and guides**, focusing on common use cases and best practices, to help users implement the new changes more effectively.
- Provide any additional explanations on breaking changes or performance improvements in v0.23.0 that might affect developers.

### **Questions I Have**:
- Are there any specific areas of the documentation that you want me to focus on more than others (e.g., API changes, new features, migration guides)?
- What are the most important points you would like highlighted in the examples and guides? 
- Are there any existing resources or guidelines I should follow to align with the project’s documentation style?
  
I believe these updates will greatly enhance the user experience and help both new and existing developers better understand and adopt the latest features of PocketBase.

Please let me know if I can be assigned to this task and any additional details or instructions you would like to include. I'm looking forward to contributing to the project!

**Best regards,**  
**Defree Harold**

**Comment by ganigeorgiev** [comment]
Thank you but I'm already working on the new documentation and I don't need help with it.

Providing guides and explanations how something should be done often takes more time than doing it on my own, especially when I'm not sure whether you are going to stick maintaning the changes in the long run (most users just abandon their opened issues and PRs; additionally I don't feel comfortable asking users to do work for me especially when I'm not paying for it).

Contribute because you want/need it, not just for the sake of the contribution.

Once the documentation for v0.23.0 is released (_there are no ETAs yet_) you are free to open PRs for the things you think that could be improved but don't expect me to create tasks for you.

**Comment by GSGSDgggdzez** [comment]
Hello Ganigeorgiev,

Thank you for your prompt response and for clarifying your current work on the documentation. I completely understand your perspective and appreciate the effort you’re putting into it.

I want to assure you that my intention to contribute comes from a genuine desire to help improve the PocketBase project, not just for the sake of making a contribution. I recognize the challenges of collaborating in open-source projects, and I respect your decision to manage the documentation on your own.

If there are any specific areas in the future where you feel additional input could be beneficial, please don’t hesitate to reach out. I’m committed to supporting the project in any way I can, whether that’s through documentation, testing, or other contributions.

Thank you again for your hard work, and I look forward to the release of v0.23.0. I’ll keep an eye out for opportunities to contribute once the documentation is available.

Best regards,

Defree Harold
