### ISSUE TITLE
Add a guide for setting up AWS for optimal combination with Pocketbase storage

### ISSUE THREAD

**Issue by GSGSDgggdzez** [pocketbase/site#69]
Hello Pocketbase team,

I would like to propose the addition of a comprehensive guide for integrating AWS services with Pocketbase, specifically focusing on optimal configuration for storage.

Currently, there isn't a dedicated resource on how to combine Pocketbase with AWS storage solutions like S3 for handling file uploads and storage. This could greatly benefit users who want to use AWS services as the backend for their Pocketbase-powered applications, ensuring a scalable and cost-effective solution.

### Suggested Content for the Guide:
- **Prerequisites**: Explanation of necessary AWS services (e.g., S3, IAM, etc.)
- **Setting up S3**: Steps to create and configure an S3 bucket for file storage.
- **Configuring Pocketbase**: Detailed instructions on how to configure Pocketbase to interact with the S3 storage service.
- **Security Best Practices**: Advice on setting up IAM roles, policies, and permissions for secure interaction between Pocketbase and AWS.
- **Cost Optimization**: Tips on how to optimize AWS storage costs, such as setting up lifecycle policies for object expiration, choosing the right storage class, etc.
- **Troubleshooting**: Common issues when combining AWS with Pocketbase and how to resolve them.

This guide would help developers who are already using Pocketbase or planning to integrate it into a larger application where AWS services are already in use.

### Additional Information:
If you need help in drafting specific steps or require a volunteer to test the guide, I am more than happy to contribute to its creation.

Thank you for considering this suggestion, and I look forward to your feedback!

**Comment by ganigeorgiev** [comment]
@GSGSDgggdzez You asked similar questions in the past, but the answer will be the same - I'm happy that you want to help, but with risk to sound rude, don't expect me to hand hold you. If you want to help do it. Not everything needs to be part of the main repo and website. It can even exists as a seperate gist, repo or even a post as ["Show and tell" discussion](https://github.com/pocketbase/pocketbase/discussions/new/choose).
