### ISSUE TITLE
About RequireSameCollectionContextAuth middleware

### ISSUE THREAD

**Issue by chnfyi** [pocketbase/site#73]
Hi,

Upgrade to v0.23 (jsvm & go) guides show `$apis.requireSameCollectionContextAuth("")` and `apis.RequireSameCollectionContextAuth("")` middlewares while they are not listed into the _Routing > Builtin middlewares_ section (js & go) from main documentation.

If i'm not wrong, it seems that this middleware is not available in jsvm. Is it on purpose ?

**Comment by ganigeorgiev** [comment]
The middleware was never exposed to the JSVM, this is just a wrong copy-paste from the Go guide.

In general this middleware is used mostly internally and as part of the tests. Let's keep it "hidden" for now to avoid confusion. In case there is demand for it I'll consider exposing it.
